# data parameters
dataset_name: vindr-normal
data_with_subfolder: False
train_data_path: ./media/vindr-normal
val_data_path:
resume: ./checkpoints/vindr-normal/hole_benchmark21_a
batch_size: 24
image_shape: [256, 256, 1]
mask_shape: [128, 200]
mask_batch_same: True
max_delta_shape: [0.25, 0.25] #relative to mask_shape
min_mask_shape: [16, 16]
margin: [0, 0]
discounted_mask: True
spatial_discounting_gamma: 0.9
random_crop: False
mask_type: hole     # hole | mosaic
mosaic_unit_size: 12
mask_csv: 
mask_func: random_bbox_rayleigh
addmask_suff: antribsegm

# training parameters
expname: benchmark21_a
cuda: True
gpu_ids: [0, 1]    # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 4
lr: 0.0001
beta1: 0.5
beta2: 0.9
n_critic: 2
niter: 500000
print_iter: 100
viz_iter: 1000
viz_max_out: 16
snapshot_save_iter: 5000

# loss weight
coarse_l1_alpha: 1.
l1_loss_alpha: 1.
ae_loss_alpha: 1.
global_wgan_loss_alpha: 1.
gan_loss_alpha: 1.
wgan_gp_lambda: 10

# network parameters
netG:
  input_dim: 1
  ngf: 32
  actv: tanh
  addmaskcoarse: True

netD:
  input_dim: 1
  ndf: 64
